//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactFormID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string title { get; set; }
        public Nullable<int> contact_form_typeID { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string special_value1 { get; set; }
        public string special_value2 { get; set; }
        public string special_value3 { get; set; }
        public Nullable<bool> special_numeric_value1 { get; set; }
        public Nullable<int> special_numeric_value2 { get; set; }
        public Nullable<int> special_numeric_value3 { get; set; }
        public string address { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    }
}
