//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int FileId { get; set; }
        public string Title { get; set; }
        public Nullable<int> TableId { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ListId { get; set; }
        public string FileUrl { get; set; }
        public string ExternalUrl { get; set; }
        public string FileType { get; set; }
        public string SpecialValue1 { get; set; }
        public string SpecialValue2 { get; set; }
        public string SpecialValue3 { get; set; }
        public string Alt { get; set; }
    }
}
