//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int elementID { get; set; }
        public Nullable<int> menuID { get; set; }
        public string menuName { get; set; }
        public Nullable<short> parentID { get; set; }
        public string imageURL { get; set; }
        public string iconURL { get; set; }
        public string linkURL { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> HasSub { get; set; }
        public Nullable<bool> HasThird { get; set; }
    
        public virtual MenuCat MenuCat { get; set; }
    }
}
