//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int PageId { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Spot { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> PageTypeId { get; set; }
        public string PrimaryImage { get; set; }
        public string HeaderImg { get; set; }
        public string Slug { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string ExternalUrl { get; set; }
        public string PageName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> ListId { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTag { get; set; }
        public Nullable<bool> has_translate { get; set; }
        public string icon { get; set; }
        public string ImgAlt { get; set; }
        public Nullable<int> masterPageId { get; set; }
    
        public virtual PageType PageType { get; set; }
    }
}
