//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsTMP
    {
        public int PostId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Description { get; set; }
        public Nullable<int> PostTypeId { get; set; }
        public Nullable<int> TagId { get; set; }
        public string PrimaryImage { get; set; }
        public string Slug { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string ExternalUrl { get; set; }
        public Nullable<int> ListId { get; set; }
        public string EmbedCode { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTag { get; set; }
        public Nullable<bool> has_translate { get; set; }
        public string TagsName { get; set; }
        public string TagsNameSlug { get; set; }
        public string ImgAlt { get; set; }
        public string SpecialValue1 { get; set; }
        public string SpecialValue2 { get; set; }
        public string SpecialValue3 { get; set; }
        public string SpecialValue4 { get; set; }
    }
}
