//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts()
        {
            this.Hashtags = new HashSet<Hashtags>();
            this.Tags = new HashSet<Tags>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Description { get; set; }
        public Nullable<int> PostTypeId { get; set; }
        public Nullable<int> TagId { get; set; }
        public string PrimaryImage { get; set; }
        public string Slug { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string ExternalUrl { get; set; }
        public Nullable<int> ListId { get; set; }
        public string EmbedCode { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTag { get; set; }
        public Nullable<bool> has_translate { get; set; }
        public string TagsName { get; set; }
        public string TagsNameSlug { get; set; }
        public string ImgAlt { get; set; }
        public string SpecialValue1 { get; set; }
        public string SpecialValue2 { get; set; }
        public string SpecialValue3 { get; set; }
        public string SpecialValue4 { get; set; }
        public string SpecialValue5 { get; set; }
        public string SpecialValue6 { get; set; }
        public string SpecialValue7 { get; set; }
        public string SpecialValue8 { get; set; }
        public Nullable<int> SpecialValue9 { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hashtags> Hashtags { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual PostType PostType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
