//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsWP
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Excerpt { get; set; }
        public string DateST { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PostType { get; set; }
        public string Permalink { get; set; }
        public string ImageURL { get; set; }
        public string Kategoriler { get; set; }
        public string SpecialValue1 { get; set; }
        public string SpecialValue2 { get; set; }
        public string SpecialValue3 { get; set; }
        public Nullable<int> PostTypeId { get; set; }
    }
}
