//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string name { get; set; }
        public Nullable<int> product_typeID { get; set; }
        public Nullable<int> order_number { get; set; }
        public string detail { get; set; }
        public string spot { get; set; }
        public string short_description { get; set; }
        public string short_description2 { get; set; }
        public string product_direction { get; set; }
        public string product_external_url { get; set; }
        public string PrimaryImage { get; set; }
        public string product_url { get; set; }
        public string product_file { get; set; }
        public Nullable<int> listID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> has_translate { get; set; }
        public string list_1 { get; set; }
        public string list_2 { get; set; }
        public string list_title_1 { get; set; }
        public string list_title_2 { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
