//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFeature
    {
        public int ProductFeatureId { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> order_number { get; set; }
        public string description { get; set; }
        public string PrimaryImage { get; set; }
        public string icon { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> productId { get; set; }
    }
}
