//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Caption1 { get; set; }
        public string Caption2 { get; set; }
        public string Caption3 { get; set; }
        public string ButtonText { get; set; }
        public string PrimaryImage { get; set; }
        public string SecondaryImage { get; set; }
        public string ExternalLink { get; set; }
        public string TextLink { get; set; }
        public Nullable<int> IsLightbox { get; set; }
        public Nullable<int> SliderCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
