//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translations
    {
        public int PageTranslationId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string TableName { get; set; }
        public string LanguageName { get; set; }
        public string CategoryName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Spot { get; set; }
        public string SpecialValue1 { get; set; }
        public string SpecialValue2 { get; set; }
        public string SpecialValue3 { get; set; }
        public string Slug { get; set; }
        public string PrimaryImage { get; set; }
        public string SecondaryImage { get; set; }
        public string VideoURL { get; set; }
        public string FileUrl { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTag { get; set; }
        public string TagsName { get; set; }
        public string TagsNameSlug { get; set; }
        public string ImgAlt { get; set; }
        public string EmbedCode { get; set; }
        public string ExternalUrl { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
