//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musahit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitId { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public Nullable<int> order_number { get; set; }
        public string name_url { get; set; }
    }
}
